FROM ubuntu:16.04
MAINTAINER RightMesh AG, https://github.com/RightMesh
RUN apt-get update && apt-get upgrade -y \
 && apt-get install -y software-properties-common \
  build-essential git \
  openjdk-8-jre openjdk-8-jdk
